services:
  api:
    build: 
      context: ./api
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - redis
  
  ws:
    build: 
      context: ./ws
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - redis

  engine:
    build: 
      context: ./engine
    restart: always
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis port
    restart: always
